import Foundation
import Testing
@testable import SwiftletCore

/// Validates the CPU reference forward pass against fixtures generated by
/// mlx-lm's qwen3_next implementation (scripts/gen_fixtures.py).
@Suite struct FixtureForwardTests {
    static let fixturesDir = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .appendingPathComponent("fixtures")

    static func maxAbsDiff(_ a: [Float], _ b: [Float]) -> Float {
        precondition(a.count == b.count, "shape mismatch: \(a.count) vs \(b.count)")
        var m: Float = 0
        for i in 0..<a.count { m = max(m, abs(a[i] - b[i])) }
        return m
    }

    @Test func tinyModelForwardMatchesMLX() throws {
        let dir = Self.fixturesDir
        let fixtures = try SafetensorsFile(url: dir.appendingPathComponent("tiny_forward.safetensors"))
        let model = try QwenCPUModel(modelDir: dir.appendingPathComponent("tiny-model"))

        let tokens = try fixtures.ints("input_ids")
        let caps = try model.forward(tokens: tokens)

        // Layer-local checks: run each layer from the REFERENCE input so f32
        // accumulation noise from earlier layers cannot pile up. This is the
        // real algorithm-correctness gate.
        let localTol: Float = 5e-4
        #expect(Self.maxAbsDiff(caps.embed, try fixtures.floats("embed")) < 1e-6, "embed mismatch")
        for i in 0..<model.config.numHiddenLayers {
            let refIn = i == 0
                ? try fixtures.floats("embed")
                : try fixtures.floats(String(format: "layer_%02d", i - 1))
            let refOut = try fixtures.floats(String(format: "layer_%02d", i))
            let localOut = try model.layerForward(refIn, S: tokens.count, layerIndex: i)
            let diff = Self.maxAbsDiff(localOut, refOut)
            #expect(diff < localTol, "layer \(i) (\(model.config.isLinearLayer(i) ? "deltanet" : "attention")) local maxAbsDiff \(diff)")
        }

        // End-to-end drift stays bounded (accumulated f32 reordering noise).
        let logitsDiff = Self.maxAbsDiff(caps.logits, try fixtures.floats("logits"))
        #expect(logitsDiff < 0.05, "logits maxAbsDiff \(logitsDiff)")

        let manifest = try JSONSerialization.jsonObject(
            with: Data(contentsOf: dir.appendingPathComponent("tiny_forward.json"))
        ) as! [String: Any]
        let expectedGreedy = manifest["greedy_next_tokens"] as! [Int]
        #expect(caps.greedy == expectedGreedy, "greedy tokens diverged")
    }

    /// qwen3_5 family variant (Qwen3.5/3.6): split DeltaNet projections,
    /// language_model.-prefixed weights, nested text_config.
    @Test func tinyQwen35ModelMatchesMLX() throws {
        let dir = Self.fixturesDir
        let fixtures = try SafetensorsFile(url: dir.appendingPathComponent("tiny_forward_q35.safetensors"))
        let model = try QwenCPUModel(modelDir: dir.appendingPathComponent("tiny-model-q35"))
        #expect(model.config.deltaLayout == .split)

        let tokens = try fixtures.ints("input_ids")
        let caps = try model.forward(tokens: tokens)

        let localTol: Float = 5e-4
        for i in 0..<model.config.numHiddenLayers {
            let refIn = i == 0
                ? try fixtures.floats("embed")
                : try fixtures.floats(String(format: "layer_%02d", i - 1))
            let refOut = try fixtures.floats(String(format: "layer_%02d", i))
            let localOut = try model.layerForward(refIn, S: tokens.count, layerIndex: i)
            let diff = Self.maxAbsDiff(localOut, refOut)
            #expect(diff < localTol, "q35 layer \(i) (\(model.config.isLinearLayer(i) ? "deltanet" : "attention")) local maxAbsDiff \(diff)")
        }

        let manifest = try JSONSerialization.jsonObject(
            with: Data(contentsOf: dir.appendingPathComponent("tiny_forward_q35.json"))
        ) as! [String: Any]
        let expectedGreedy = manifest["greedy_next_tokens"] as! [Int]
        #expect(caps.greedy == expectedGreedy, "q35 greedy tokens diverged")
    }

    /// Same forward pass through the int4-quantized tiny model: exercises the
    /// MLX affine dequantization path (packed uint32 + scales/biases).
    @Test func tinyQuantizedModelMatchesMLX() throws {
        let dir = Self.fixturesDir
        let fixtures = try SafetensorsFile(url: dir.appendingPathComponent("tiny_forward_q4.safetensors"))
        let model = try QwenCPUModel(modelDir: dir.appendingPathComponent("tiny-model-q4"))

        let tokens = try fixtures.ints("input_ids")
        let caps = try model.forward(tokens: tokens, captureLayers: false)

        let logitsDiff = Self.maxAbsDiff(caps.logits, try fixtures.floats("logits"))
        #expect(logitsDiff < 2e-3, "quantized logits maxAbsDiff \(logitsDiff)")

        let manifest = try JSONSerialization.jsonObject(
            with: Data(contentsOf: dir.appendingPathComponent("tiny_forward_q4.json"))
        ) as! [String: Any]
        let expectedGreedy = manifest["greedy_next_tokens"] as! [Int]
        #expect(caps.greedy == expectedGreedy, "quantized greedy tokens diverged")
    }
}
